"""Course-grounded concepts, edges, misconceptions, lessons, twin catalog."""

from .knowledge_extra import EXTRA_CONCEPTS, EXTRA_MISCONCEPTIONS

CONCEPTS = [
    {
        "slug": "multimodal-ai",
        "name": "Multimodal AI",
        "cluster": "fundamentals",
        "school": "A model that looks at more than one kind of signal — like a camera picture and a LiDAR distance map — to answer one question.",
        "engineer": "Architectures that ingest heterogeneous tensors (RGB, XYZA, audio spectrograms, CT volumes, PDF layout, video chunks) and fuse or align them for a shared task.",
        "research": "Complementary information theory: fusion helps only when modalities carry uncorrelated residual signal; otherwise the extra stream is ignored or causes overfitting.",
        "twin_id": "fusion-lab",
        "source": {"source_type": "notebook", "file": "01a_Early_and_Late_Fusion.ipynb", "cell_index": 2},
        "misconceptions": ["fusion-always-wins"],
    },
    {
        "slug": "omniverse-sdg",
        "name": "Omniverse synthetic data",
        "cluster": "fundamentals",
        "school": "Instead of driving a robot around the world, NVIDIA Omniverse can spawn a digital twin of cubes and cameras and save perfectly paired RGB and LiDAR.",
        "engineer": "Replicator generates aligned rgb/, lidar/, distance/, positions.csv, azimuth.npy, zenith.npy for supervised multimodal training.",
        "research": "Sim-to-real gap remains: Omniverse units are relative; lighting and LiDAR noise models may not match a physical sensor.",
        "twin_id": "lidar-geometry",
        "source": {"source_type": "notebook", "file": "01a_Early_and_Late_Fusion.ipynb", "cell_index": 8},
        "misconceptions": ["omniverse-is-the-kit-app-in-this-repo"],
    },
    {
        "slug": "digital-twin",
        "name": "Digital twin",
        "cluster": "fundamentals",
        "school": "A virtual copy of a real object or place you can instrument with fake cameras and LiDAR.",
        "engineer": "Course uses twins for SDG. This academy also uses educational twins (simulated metrics labeled SIMULATED_RESULT).",
        "research": "Do not confuse SDG twins with operational twins fed by live DCGM telemetry.",
        "twin_id": "fusion-lab",
        "source": {"source_type": "notebook", "file": "01a_Early_and_Late_Fusion.ipynb", "cell_index": 8},
        "misconceptions": ["simulation-is-actual"],
    },
    {
        "slug": "rgb-camera",
        "name": "RGB camera",
        "cluster": "sensors",
        "school": "A grid of red/green/blue brightness — great for color, weaker for measuring true distance, especially in the dark.",
        "engineer": "64×64 PNG in the lab; 4-channel tensors after ToTensor (including alpha in some loads). Analyzed with Conv2d CNNs.",
        "research": "Photometric ambiguity: many 3D layouts can produce similar RGB.",
        "twin_id": "fusion-lab",
        "source": {"source_type": "notebook", "file": "01a_Early_and_Late_Fusion.ipynb", "cell_index": 9},
        "misconceptions": ["rgb-gives-metric-depth"],
    },
    {
        "slug": "lidar",
        "name": "LiDAR",
        "cluster": "sensors",
        "school": "The sensor shouts light and times the echo to learn how far something is. It does not see red vs blue.",
        "engineer": "Simulated 64×64 beam grid; azimuth on rows, zenith on columns for this particular system — not universal.",
        "research": "Beam geometry, max-range sentinel, and angular conventions are vendor-specific.",
        "twin_id": "lidar-geometry",
        "source": {"source_type": "notebook", "file": "01a_Early_and_Late_Fusion.ipynb", "cell_index": 14},
        "misconceptions": ["lidar-sees-color", "all-lidar-share-this-math"],
    },
    {
        "slug": "azimuth",
        "name": "Azimuth",
        "cluster": "lidar",
        "school": "How far you spun left/right from 'straight ahead' before firing the laser.",
        "engineer": "Horizontal angle; in 01a azimuth ↔ rows. Measured positive counterclockwise from the sensor forward in this dataset.",
        "research": "Aerospace vs robotics conventions differ; always read the sensor ICD.",
        "twin_id": "lidar-geometry",
        "source": {"source_type": "notebook", "file": "01a_Early_and_Late_Fusion.ipynb", "cell_index": 16},
        "misconceptions": ["azimuth-is-zenith"],
    },
    {
        "slug": "zenith",
        "name": "Zenith",
        "cluster": "lidar",
        "school": "How far you tilted up/down from the azimuth horizon.",
        "engineer": "Vertical angle; 01a zenith ↔ columns. Measured positive clockwise from the azimuth direction in this system.",
        "research": "Elevation vs zenith naming is a common paper-level confusion.",
        "twin_id": "lidar-geometry",
        "source": {"source_type": "notebook", "file": "01a_Early_and_Late_Fusion.ipynb", "cell_index": 16},
        "misconceptions": ["azimuth-is-zenith"],
    },
    {
        "slug": "lidar-xyza",
        "name": "LiDAR XYZA",
        "cluster": "lidar",
        "school": "Turn each ping into a 3D point plus a flag that says 'this ping actually hit something'.",
        "engineer": "x = d sin(-az) cos(-ze); y = d cos(-az) cos(-ze); z = d sin(-ze); a = 1[d < 50]. Stack as 4-channel tensor.",
        "research": "The minus signs are a convention chosen to match RGB; dropping them rotates the cloud.",
        "twin_id": "lidar-geometry",
        "source": {"source_type": "notebook", "file": "01a_Early_and_Late_Fusion.ipynb", "cell_index": 39},
        "misconceptions": ["xyza-is-rgb"],
    },
    {
        "slug": "max-range-mask",
        "name": "Max-range mask",
        "cluster": "lidar",
        "school": "If the echo never comes back, the sensor pretends the world is at max distance. You must hide those fake points.",
        "engineer": "a = 1 where depth < 50 else 0 (01a). Visualizations scatter only a==1.",
        "research": "Sentinel values can dominate MSE if left in the tensor.",
        "twin_id": "lidar-geometry",
        "source": {"source_type": "notebook", "file": "01a_Early_and_Late_Fusion.ipynb", "cell_index": 27},
        "misconceptions": ["max-range-is-a-real-hit"],
    },
    {
        "slug": "cnn-position",
        "name": "CNN position regressor",
        "cluster": "models",
        "school": "Three convolution+pool stages then dense layers that output 9 numbers: xyz for three objects.",
        "engineer": "Net: Conv 50/100/200, MaxPool2d(2) thrice, Linear(200*8*8 → 1000 → 100 → 9). in_ch 4 (RGB or XYZA) or 8 (early fusion).",
        "research": "Shared spatial resolution of RGB and projected LiDAR is a lab convenience, not a law.",
        "twin_id": "fusion-lab",
        "source": {"source_type": "notebook", "file": "01a_Early_and_Late_Fusion.ipynb", "cell_index": 49},
        "misconceptions": ["same-shape-means-same-information"],
    },
    {
        "slug": "mse-as-distance",
        "name": "MSE as distance",
        "cluster": "models",
        "school": "Training minimizes squared error, which is Pythagoras without the square root — still pushes predicted centers toward true centers.",
        "engineer": "nn.MSELoss on 9-D position vectors. Minimizing MSE also minimizes RMSE monotonically.",
        "research": "MSE is rotation-sensitive in object-slot ordering; permutation of the three objects can inflate loss.",
        "twin_id": "fusion-lab",
        "source": {"source_type": "notebook", "file": "01a_Early_and_Late_Fusion.ipynb", "cell_index": 50},
        "misconceptions": ["mse-is-classification-loss"],
    },
    {
        "slug": "late-fusion",
        "name": "Late fusion",
        "cluster": "fusion",
        "school": "Each sense thinks alone, then you glue their final guesses together.",
        "engineer": "Frozen or jointly trained unimodal Nets; concatenate 9+9 activations; MLP to 9. 01a freezes pretrained heads; 02a trains LateNet from scratch.",
        "research": "Late fusion cannot create mid-level interactions (color×geometry features).",
        "twin_id": "fusion-lab",
        "source": {"source_type": "notebook", "file": "01a_Early_and_Late_Fusion.ipynb", "cell_index": 59},
        "misconceptions": ["late-equals-ensemble-always-best", "late-vs-early-universal-winner"],
    },
    {
        "slug": "early-fusion",
        "name": "Early fusion",
        "cluster": "fusion",
        "school": "Stack the pictures like extra color channels and let one CNN look at the stack.",
        "engineer": "torch.cat(rgb, xyza, dim=1) → Net(8). Same spatial CNN as unimodal.",
        "research": "Requires spatially aligned modalities; LiDAR must already be rasterized like the image.",
        "twin_id": "fusion-lab",
        "source": {"source_type": "notebook", "file": "01a_Early_and_Late_Fusion.ipynb", "cell_index": 63},
        "misconceptions": ["late-vs-early-universal-winner"],
    },
    {
        "slug": "intermediate-concat",
        "name": "Intermediate concat fusion",
        "cluster": "fusion",
        "school": "Each sense looks with its own filters for a while, then you stack those filter maps before the final brain.",
        "engineer": "ConcatIntermediateNet: two conv towers 25-50-100, cat on channel dim to 200×8×8, then MLP. Fewer params than LateNet.",
        "research": "Join depth is a hyperparameter; concat preserves both feature sets linearly.",
        "twin_id": "fusion-lab",
        "source": {"source_type": "notebook", "file": "02a_Intermediate_Fusion.ipynb", "cell_index": 25},
        "misconceptions": ["more-parameters-always-better"],
    },
    {
        "slug": "intermediate-matmul",
        "name": "Intermediate matmul fusion",
        "cluster": "fusion",
        "school": "Instead of stacking maps, multiply them so every RGB location can talk to every LiDAR location in that grid.",
        "engineer": "MatmulIntermediateNet: torch.matmul(x_rgb, x_xyz) then flatten 100×8×8. Distinct from Hadamard (elementwise) product.",
        "research": "Matmul increases mixing; also increases risk of spatial-aliasing artifacts.",
        "twin_id": "fusion-lab",
        "source": {"source_type": "notebook", "file": "02a_Intermediate_Fusion.ipynb", "cell_index": 28},
        "misconceptions": ["matmul-is-hadamard"],
    },
    {
        "slug": "colored-cubes-task",
        "name": "Colored cubes task",
        "cluster": "fusion",
        "school": "Three cubes that only differ by color. Distance-only LiDAR cannot tell who is who; the camera can.",
        "engineer": "RGB valid loss ~6 (~2 units/object). LiDAR train<1 valid>8 = overfitting. Spawn box 10³ units, diagonal ~17.3.",
        "research": "Classic complementary-modality benchmark constructed via Omniverse.",
        "twin_id": "fusion-lab",
        "source": {"source_type": "notebook", "file": "02a_Intermediate_Fusion.ipynb", "cell_index": 5},
        "misconceptions": ["lidar-sees-color", "fusion-always-wins"],
    },
    {
        "slug": "overfitting-lidar",
        "name": "LiDAR overfitting on color tasks",
        "cluster": "fusion",
        "school": "The LiDAR model memorizes training rooms because it never saw the color rule.",
        "engineer": "Train loss << valid loss on cubes-only LiDAR. Pattern absence, not merely small data.",
        "research": "Memorization vs generalization diagnostic before blaming optimizer.",
        "twin_id": "fusion-lab",
        "source": {"source_type": "notebook", "file": "02a_Intermediate_Fusion.ipynb", "cell_index": 7},
        "misconceptions": ["low-train-loss-means-solved"],
    },
    {
        "slug": "spectrogram",
        "name": "Spectrogram",
        "cluster": "modalities",
        "school": "A heat-map of sound: time across, pitch up, brightness = loudness — then a CNN can 'see' audio.",
        "engineer": "WAV amplitude + STFT/specgram. Stereo = 2 channels. Nyquist = sample_rate/2.",
        "research": "Phase is discarded in magnitude spectrograms; some tasks need complex STFT.",
        "twin_id": "modality-explorer",
        "source": {"source_type": "notebook", "file": "01b_Exploring_Modalities.ipynb", "cell_index": 11},
        "misconceptions": ["audio-cannot-use-cnns"],
    },
    {
        "slug": "nyquist",
        "name": "Nyquist limit",
        "cluster": "modalities",
        "school": "You cannot honestly hear a whistle faster than half your recording speed.",
        "engineer": "Highest reliable frequency is 0.5 × sample rate (01b).",
        "research": "Aliasing vs reconstruction filters in ADC design.",
        "twin_id": "modality-explorer",
        "source": {"source_type": "notebook", "file": "01b_Exploring_Modalities.ipynb", "cell_index": 7},
        "misconceptions": ["higher-bitrate-is-nyquist"],
    },
    {
        "slug": "ct-nifti",
        "name": "CT / NIfTI",
        "cluster": "modalities",
        "school": "A CT scan is a loaf of X-ray slices. NIfTI is the file box those slices live in.",
        "engineer": "nibabel load → 3D array; rot90 for orientation; animate along an axis. U-Net cited for anomalies.",
        "research": "Affine headers encode patient space; ignoring them misregisters multimodal MRI/CT.",
        "twin_id": "modality-explorer",
        "source": {"source_type": "notebook", "file": "01b_Exploring_Modalities.ipynb", "cell_index": 17},
        "misconceptions": ["ct-is-2d-xray"],
    },
    {
        "slug": "unet",
        "name": "U-Net",
        "cluster": "modalities",
        "school": "A CNN that paints a highlight on the weird spots in a medical image instead of just naming the whole picture.",
        "engineer": "Encoder–decoder with skip connections for dense biomedical segmentation (cited 01b, arXiv:1505.04597).",
        "research": "3D U-Nets operate on volumetric CT; 2D CNNs lose through-plane context.",
        "twin_id": "modality-explorer",
        "source": {"source_type": "notebook", "file": "01b_Exploring_Modalities.ipynb", "cell_index": 32},
        "misconceptions": ["unet-is-just-vgg"],
    },
    {
        "slug": "cosine-similarity",
        "name": "Cosine similarity",
        "cluster": "contrastive",
        "school": "How aligned two arrows are, ignoring how long they are.",
        "engineer": "dot(a,b)/(||a|| ||b||). 02b rescales (cos+1)/2 into [0,1] before CE.",
        "research": "Cosine is invariant to positive scaling; not a metric in the strict sense.",
        "twin_id": "contrastive-space",
        "source": {"source_type": "notebook", "file": "02b_Contrastive_Pretraining.ipynb", "cell_index": 25},
        "misconceptions": ["cosine-is-euclidean"],
    },
    {
        "slug": "sobel-outline",
        "name": "Sobel outlines",
        "cluster": "contrastive",
        "school": "A tiny stencil that finds edges so a photo becomes a sketch you can search with.",
        "engineer": "Gx/Gy 3×3 kernels, conv2d, threshold 0.25, nonzero→1. FashionMNIST paired views.",
        "research": "Sobel is a linear approximation of image gradient; not a learned tokenizer.",
        "twin_id": "contrastive-space",
        "source": {"source_type": "notebook", "file": "02b_Contrastive_Pretraining.ipynb", "cell_index": 8},
        "misconceptions": ["sobel-is-the-embedder"],
    },
    {
        "slug": "clip-style",
        "name": "CLIP-style contrastive pre-training",
        "cluster": "contrastive",
        "school": "Teach two different cameras to point their arrows the same way for the same object, and apart for different objects.",
        "engineer": "Two ImgEmbedders, all-pairs cosine via repeat_interleave/repeat, unflatten to B×B, symmetric CrossEntropy vs arange(B).",
        "research": "InfoNCE family; temperature/logit scale omitted in 02b (manual [0,1] map).",
        "twin_id": "contrastive-space",
        "source": {"source_type": "notebook", "file": "02b_Contrastive_Pretraining.ipynb", "cell_index": 38},
        "misconceptions": ["clip-is-only-text-image", "contrastive-is-classification-of-classes"],
    },
    {
        "slug": "vector-lookup",
        "name": "Vector lookup",
        "cluster": "contrastive",
        "school": "Draw a sketch, turn it into an arrow, find the photo whose arrow is closest.",
        "engineer": "outlineEmbedder(query) vs batched baseImgEmbedder; argmax cosine. Prototype of RAG retrieval.",
        "research": "Brute-force scan; production systems use ANN indexes (not built in 02b).",
        "twin_id": "contrastive-space",
        "source": {"source_type": "notebook", "file": "02b_Contrastive_Pretraining.ipynb", "cell_index": 45},
        "misconceptions": ["vector-db-updates-the-cnn-weights"],
    },
    {
        "slug": "cross-modal-projection",
        "name": "Cross-modal projection",
        "cluster": "projection",
        "school": "A translator that turns one language of arrows into another so you can reuse a brain that only speaks the second language.",
        "engineer": "MLP mapping embedding A → embedding B; freeze B's encoder/head. 03a projects text into VGG/CLIP image space (opposite of common CLIP image→text talk).",
        "research": "Least-squares alignment of representation spaces; distribution shift still bites.",
        "twin_id": "projection-lab",
        "source": {"source_type": "notebook", "file": "03a_Projection.ipynb", "cell_index": 1},
        "misconceptions": ["projection-is-fusion", "projection-requires-unfreezing"],
    },
    {
        "slug": "vgg16-embedder",
        "name": "VGG16 as embedder",
        "cluster": "projection",
        "school": "A famous photo-brain whose inner numbers we steal as a 4096-long description.",
        "engineer": "Frozen vgg.features+avgpool+classifier[0:3] → 4096-d; new head 4096→500→3 flower classes.",
        "research": "Pretrained ImageNet features transfer; tiny flower set is intentionally overfit in 03a to prove capacity.",
        "twin_id": "projection-lab",
        "source": {"source_type": "notebook", "file": "03a_Projection.ipynb", "cell_index": 23},
        "misconceptions": ["must-train-vgg-from-scratch"],
    },
    {
        "slug": "ocr",
        "name": "OCR",
        "cluster": "documents",
        "school": "Reading letters that live inside pictures of pages.",
        "engineer": "unstructured.partition_pdf + Tesseract when text is not already in the PDF operators.",
        "research": "Layout-aware OCR vs raw Tesseract; reading order errors poison RAG.",
        "twin_id": "ocr-pipeline",
        "source": {"source_type": "notebook", "file": "03b_OCR_Pipelines.ipynb", "cell_index": 1},
        "misconceptions": ["pdf-text-is-always-extractable"],
    },
    {
        "slug": "chunking-by-title",
        "name": "by_title chunking",
        "cluster": "documents",
        "school": "Cut the document at section titles so each piece is about one idea, not a random character budget.",
        "engineer": "partition_pdf(..., chunking_strategy='by_title', max_characters=2000, new_after_n_chars=1800, combine_text_under_n_chars=1000).",
        "research": "Semantic chunking still lags learned splitters; by_title is a strong baseline.",
        "twin_id": "ocr-pipeline",
        "source": {"source_type": "notebook", "file": "03b_OCR_Pipelines.ipynb", "cell_index": 12},
        "misconceptions": ["bigger-chunks-always-better"],
    },
    {
        "slug": "table-transformer",
        "name": "Table Transformer",
        "cluster": "documents",
        "school": "A detector that finds spreadsheet-looking regions and turns them into HTML.",
        "engineer": "infer_table_structure=True, strategy='hi_res' → microsoft/table-transformer-structure-recognition; text_as_html for LangChain Documents.",
        "research": "Rows can still be dropped; markdown or table-as-image fallbacks are discussed.",
        "twin_id": "ocr-pipeline",
        "source": {"source_type": "notebook", "file": "03b_OCR_Pipelines.ipynb", "cell_index": 19},
        "misconceptions": ["html-tables-are-perfect"],
    },
    {
        "slug": "yolox",
        "name": "YOLOX layout detection",
        "cluster": "documents",
        "school": "A one-look object detector that draws boxes around figures and tables on a page.",
        "engineer": "Anchor-free YOLO; unstructured hi_res_model_name='yolox'; extract_image_block_types Image/Table.",
        "research": "YOLOX-L fine-tune on Digital Corpora + Azure DI labels (NV-YOLOX card).",
        "twin_id": "ocr-pipeline",
        "source": {"source_type": "notebook", "file": "03b_OCR_Pipelines.ipynb", "cell_index": 27},
        "misconceptions": ["yolo-is-an-llm"],
    },
    {
        "slug": "nv-yolox-page-elements",
        "name": "NV-YOLOX page elements",
        "cluster": "documents",
        "school": "NVIDIA's page reader that labels tables, charts, and titles with boxes.",
        "engineer": "nvidia/nv-yolox-page-elements-v1 HTTP API; labels table/chart/title; normalized x_min..y_max.",
        "research": "Chart ⊆ {bar, line, pie} per course definition.",
        "twin_id": "ocr-pipeline",
        "source": {"source_type": "notebook", "file": "03b_OCR_Pipelines.ipynb", "cell_index": 41},
        "misconceptions": ["nv-yolox-reads-the-words"],
    },
    {
        "slug": "pdf-batching",
        "name": "PDF raster batching",
        "cluster": "documents",
        "school": "Don't dump a giant PDF into memory; convert a few pages at a time.",
        "engineer": "pdf2image convert_from_path with CHUNK_SIZE and first_page/last_page; dpi tradeoff.",
        "research": "Memory vs OCR accuracy (dpi) is an ops constraint, not a model one.",
        "twin_id": "ocr-pipeline",
        "source": {"source_type": "notebook", "file": "03b_OCR_Pipelines.ipynb", "cell_index": 55},
        "misconceptions": ["convert-from-path-is-free"],
    },
    {
        "slug": "vss",
        "name": "NVIDIA VSS",
        "cluster": "vss",
        "school": "A ready-made video brain: upload a clip, get a summary, then ask questions.",
        "engineer": "Video Search and Summarization AI Blueprint. REST: /files, /summarize, /health/ready, /models, /chat/completions. Default VLM vila-1.5.",
        "research": "Reference NIM pipeline; not a single monolithic network.",
        "twin_id": "vss-pipeline",
        "source": {"source_type": "notebook", "file": "04a_VSS.ipynb", "cell_index": 1},
        "misconceptions": ["vss-is-one-llm-call"],
    },
    {
        "slug": "ca-rag",
        "name": "CA-RAG",
        "cluster": "vss",
        "school": "The summary is not the VLM ranting alone — an LLM is fed the VLM's notes plus a vector notebook of those notes.",
        "engineer": "Context-Aware RAG: VLM dense captions → caption summarization LLM (batched) → summary aggregation LLM; embeddings stored in Milvus.",
        "research": "Batch size of caption summarization is launch-time YAML, not only REST.",
        "twin_id": "vss-pipeline",
        "source": {"source_type": "notebook", "file": "04a_VSS.ipynb", "cell_index": 33},
        "misconceptions": ["summary-can-invent-unseen-details"],
    },
    {
        "slug": "vss-chunk-duration",
        "name": "VSS chunk duration",
        "cluster": "vss",
        "school": "How many seconds the video brain looks at in one gulp. Short gulps catch a speeding car; long gulps finish faster.",
        "engineer": "N_chunks ≈ video_s / chunk_s; processed_frames = frames_per_chunk * N_chunks (default 10 frames/chunk). Typical 10–60s. chunk_overlap_duration for boundary events.",
        "research": "Stride with overlap is video_s / (chunk - overlap).",
        "twin_id": "vss-pipeline",
        "source": {"source_type": "notebook", "file": "04a_VSS.ipynb", "cell_index": 60},
        "misconceptions": ["longer-chunks-always-better", "frames-per-chunk-scales-automatically"],
    },
    {
        "slug": "vlm-prompt-persona",
        "name": "VLM prompt persona",
        "cluster": "vss",
        "school": "Tell the video model who it is (traffic cop) and how to write (start/end timestamps) or it will give a vague movie recap.",
        "engineer": "Three-part prompt: persona, details, format. Caption_summarization_prompt condenses; summary_aggregation_prompt formats the report.",
        "research": "Missing details in dense captions cannot be recovered later — inspect Milvus first.",
        "twin_id": "vss-pipeline",
        "source": {"source_type": "notebook", "file": "04a_VSS.ipynb", "cell_index": 48},
        "misconceptions": ["aggregation-prompt-creates-new-facts"],
    },
    {
        "slug": "vss-temperature",
        "name": "VSS temperature / top_p",
        "cluster": "vss",
        "school": "High temperature makes the writer more creative — bad when you need a factual traffic log.",
        "engineer": "Low T and top_p for repeatability / fewer hallucinations; high for variety. max_tokens truncates long reports.",
        "research": "Sampling params apply to LLM stages; VLM caption noise is a separate axis.",
        "twin_id": "vss-pipeline",
        "source": {"source_type": "notebook", "file": "04a_VSS.ipynb", "cell_index": 68},
        "misconceptions": ["temperature-changes-chunk-size"],
    },
    {
        "slug": "milvus-captions",
        "name": "Milvus dense captions",
        "cluster": "vss",
        "school": "A filing cabinet of what the VLM said about each chunk, used later for Q&A.",
        "engineer": "Collection summary_till_now_{id}; pymilvus at via-server:19530. Inspect captions when summaries lack events.",
        "research": "Vector RAG quality is bounded by caption coverage.",
        "twin_id": "vss-pipeline",
        "source": {"source_type": "notebook", "file": "04a_VSS.ipynb", "cell_index": 35},
        "misconceptions": ["milvus-stores-raw-video"],
    },
    {
        "slug": "vector-rag",
        "name": "Vector-RAG (VSS Q&A)",
        "cluster": "graphrag",
        "school": "Find the five most similar video notes, shuffle the best ones to the front, then let an LLM answer.",
        "engineer": "Top-5 Milvus chunks, rerank llama-3.2-nv-rerankqa-1b-v2, LLM answer. Only method for live streams.",
        "research": "Fails on multi-hop relations not present in a single caption neighborhood.",
        "twin_id": "graph-rag",
        "source": {"source_type": "notebook", "file": "04b_VSS_GraphRAG.ipynb", "cell_index": 1},
        "misconceptions": ["vector-rag-equals-graph-rag"],
    },
    {
        "slug": "graph-rag",
        "name": "Graph-RAG",
        "cluster": "graphrag",
        "school": "Turn the video notes into a map of who did what to whom, then walk the map to answer.",
        "engineer": "LLM extracts nodes/edges to Neo4j; embeddings (llama-3.2-nv-embedqa-1b-v2 / nv-embedqa-e5-v5 in 04b text) linked to entities. enable_chat=True at summarize.",
        "research": "Graph construction errors propagate; Cypher names must match generated types.",
        "twin_id": "graph-rag",
        "source": {"source_type": "notebook", "file": "04b_VSS_GraphRAG.ipynb", "cell_index": 1},
        "misconceptions": ["vector-rag-equals-graph-rag", "graph-rag-for-live-stream"],
    },
    {
        "slug": "g-extraction",
        "name": "G-Extraction",
        "cluster": "graphrag",
        "school": "Read a caption and list the people, objects, and arrows between them.",
        "engineer": "Dense caption → entities/relations → Neo4j nodes/edges.",
        "research": "Open IE quality depends on caption granularity and ontology prompt.",
        "twin_id": "graph-rag",
        "source": {"source_type": "notebook", "file": "04b_VSS_GraphRAG.ipynb", "cell_index": 19},
        "misconceptions": ["extraction-is-cypher"],
    },
    {
        "slug": "g-retriever",
        "name": "G-Retriever",
        "cluster": "graphrag",
        "school": "Turn an English question into a graph search (Cypher).",
        "engineer": "LLM maps 'what caused the box to fall?' to MATCH ... RETURN paths.",
        "research": "Text-to-Cypher is brittle; notebooks warn you may need to edit relationship names.",
        "twin_id": "graph-rag",
        "source": {"source_type": "notebook", "file": "04b_VSS_GraphRAG.ipynb", "cell_index": 20},
        "misconceptions": ["extraction-is-cypher"],
    },
    {
        "slug": "g-generation",
        "name": "G-Generation",
        "cluster": "graphrag",
        "school": "Write a normal sentence from the little subgraph you fetched.",
        "engineer": "LLM synthesizes nodes, relations, and linked captions into the chat answer.",
        "research": "Grounding still needed; graph hits can be incomplete.",
        "twin_id": "graph-rag",
        "source": {"source_type": "notebook", "file": "04b_VSS_GraphRAG.ipynb", "cell_index": 21},
        "misconceptions": ["generation-invents-edges"],
    },
    {
        "slug": "enable-chat",
        "name": "enable_chat",
        "cluster": "graphrag",
        "school": "A switch on summarize that also builds the knowledge graph for later questions.",
        "engineer": "POST /summarize with enable_chat True (04b). summarize may be False if you only need the graph.",
        "research": "Cost: extra LLM extraction at ingest time.",
        "twin_id": "graph-rag",
        "source": {"source_type": "notebook", "file": "04b_VSS_GraphRAG.ipynb", "cell_index": 12},
        "misconceptions": ["chat-works-without-ingest"],
    },
    {
        "slug": "cilp",
        "name": "CILP",
        "cluster": "assessment",
        "school": "CLIP's cousin: teach a camera and a LiDAR to agree on cubes vs spheres so you can classify photos with a LiDAR-trained brain.",
        "engineer": "Contrastive Image LiDAR Pre-training. Embedder in_ch 4 vs 1, emb 200, CosineSimilarity, repeat_interleave/repeat, mean of two CEs. Target valid loss < 3.5 (aim 3.2).",
        "research": "Paired SDG is privileged; unpaired RGB-LiDAR would need different objectives.",
        "twin_id": "cilp-assessment",
        "source": {"source_type": "notebook", "file": "05_Assessment.ipynb", "cell_index": 2},
        "misconceptions": ["cilp-classifies-directly", "clip-is-only-text-image"],
    },
    {
        "slug": "frozen-lidar-cnn",
        "name": "Frozen LiDAR CNN",
        "cluster": "assessment",
        "school": "The old LiDAR classifier's weights stay locked; we only learn a translator from photos into its language.",
        "engineer": "Classifier(1) load lidar_cnn.pt; requires_grad False. Projector maps CILP image emb → get_embs size; RGB2LiDARClassifier uses img_embedder.",
        "research": "Zero-shot projector should already exceed ~70% before 5-epoch fine-tune to >95%.",
        "twin_id": "cilp-assessment",
        "source": {"source_type": "notebook", "file": "05_Assessment.ipynb", "cell_index": 8},
        "misconceptions": ["unfreeze-to-pass", "projection-requires-unfreezing"],
    },
    {
        "slug": "assessment-gates",
        "name": "Assessment gates",
        "cluster": "assessment",
        "school": "Pass/fail numbers: contrastive loss low enough, then five photo batches classified almost perfectly.",
        "engineer": "5 pts CILP valid loss < 3.5 (re-eval on server; notebook 3.2); 5×1 pts batch acc > 0.95; 9/10 to pass. run_assessment(CILP_model, projector).",
        "research": "Server re-evaluation implies you must not overfit the visible valid split with leaked tricks.",
        "twin_id": "cilp-assessment",
        "source": {"source_type": "notebook", "file": "05_Assessment.ipynb", "cell_index": 46},
        "misconceptions": ["9-points-optional"],
    },
    {
        "slug": "nim",
        "name": "NVIDIA NIM",
        "cluster": "platform",
        "school": "A packaged GPU microservice that speaks a familiar HTTP API so you can call VILA or an LLM without assembling CUDA yourself.",
        "engineer": "Course VSS uses NIMs for VLM/LLM. This academy's tutor can target NIM_BASE_URL (OpenAI-compatible) as a provider — not the same as VSS via-server.",
        "research": "Compatibility ≠ identical sampling/telemetry fields.",
        "twin_id": "vss-pipeline",
        "source": {"source_type": "notebook", "file": "04a_VSS.ipynb", "cell_index": 1},
        "misconceptions": ["nim-is-vllm-product-name"],
    },
    {
        "slug": "evidence-types",
        "name": "Evidence types",
        "cluster": "platform",
        "school": "A label that says whether a number came from NVIDIA's notes, a guess in the notebook, a fake twin, a real run, or the tutor thinking.",
        "engineer": "COURSE_SOURCE, EXPECTED_RESULT, SIMULATED_RESULT, ACTUAL_RUN, TUTOR_INTERPRETATION, EXTERNAL_RESEARCH.",
        "research": "Scientific integrity for learning systems; prevents simulation laundering.",
        "twin_id": "fusion-lab",
        "source": {"source_type": "notebook", "file": "02a_Intermediate_Fusion.ipynb", "cell_index": 5},
        "misconceptions": ["simulation-is-actual"],
    },
]

CONCEPTS = CONCEPTS + EXTRA_CONCEPTS
for _c in CONCEPTS:
    _c.setdefault("analogy", (_c.get("school") or "").split(".")[0])

EDGES = [
    ("omniverse-sdg", "rgb-camera", "GENERATES", "paired RGB"),
    ("omniverse-sdg", "lidar", "GENERATES", "paired LiDAR"),
    ("omniverse-sdg", "digital-twin", "IMPLEMENTED_IN", "Replicator scenes"),
    ("azimuth", "lidar-xyza", "PART_OF", "x,y depend on azimuth"),
    ("zenith", "lidar-xyza", "PART_OF", "z and radial shrink"),
    ("max-range-mask", "lidar-xyza", "CONTROLS", "valid a channel"),
    ("lidar-xyza", "early-fusion", "PREREQUISITE_OF", "must rasterize first"),
    ("rgb-camera", "early-fusion", "PART_OF", "channel stack"),
    ("late-fusion", "cnn-position", "DEPENDS_ON", "unimodal heads"),
    ("early-fusion", "cnn-position", "DEPENDS_ON", "Net(8)"),
    ("colored-cubes-task", "overfitting-lidar", "CAN_CAUSE", "no color channel"),
    ("colored-cubes-task", "intermediate-concat", "MOTIVATES", "need mid fusion"),
    ("intermediate-matmul", "intermediate-concat", "COMPARES_WITH", "join operator"),
    ("late-fusion", "early-fusion", "COMPARES_WITH", "join time"),
    ("mse-as-distance", "cnn-position", "MEASURES", "position error"),
    ("spectrogram", "nyquist", "DEPENDS_ON", "sample rate"),
    ("ct-nifti", "unet", "DIAGNOSED_BY", "segmentation"),
    ("sobel-outline", "clip-style", "PREREQUISITE_OF", "paired view"),
    ("cosine-similarity", "clip-style", "MEASURES", "pair match"),
    ("clip-style", "vector-lookup", "ENABLES", "retrieve by outline"),
    ("clip-style", "cilp", "COMPARES_WITH", "same objective family"),
    ("cross-modal-projection", "vgg16-embedder", "DEPENDS_ON", "frozen image space"),
    ("cross-modal-projection", "cilp", "PREREQUISITE_OF", "assessment projector"),
    ("ocr", "chunking-by-title", "PART_OF", "RAG prep"),
    ("table-transformer", "ocr", "PART_OF", "tables"),
    ("yolox", "nv-yolox-page-elements", "COMPARES_WITH", "generic vs NVIDIA page model"),
    ("vss", "ca-rag", "IMPLEMENTED_IN", "summarize pipeline"),
    ("vss-chunk-duration", "ca-rag", "CONTROLS", "caption granularity"),
    ("vlm-prompt-persona", "ca-rag", "CONTROLS", "caption content"),
    ("milvus-captions", "vector-rag", "EVIDENCED_BY", "chunk vectors"),
    ("vector-rag", "graph-rag", "COMPARES_WITH", "Q&A backends"),
    ("g-extraction", "graph-rag", "PART_OF", "index"),
    ("g-retriever", "graph-rag", "PART_OF", "query"),
    ("g-generation", "graph-rag", "PART_OF", "answer"),
    ("enable-chat", "graph-rag", "CONTROLS", "graph build"),
    ("cilp", "frozen-lidar-cnn", "OPTIMIZES", "reuse head"),
    ("assessment-gates", "cilp", "MEASURES", "loss/acc"),
    ("lidar", "rgb-camera", "CONFUSED_WITH", "both 64x64 in lab"),
    ("early-fusion", "late-fusion", "CONFUSED_WITH", "join timing"),
    ("graph-rag", "vector-rag", "CONFUSED_WITH", "both called RAG"),
    ("vss-temperature", "vss-chunk-duration", "CONFUSED_WITH", "both are summarize knobs"),
    ("nim", "vss", "IMPLEMENTED_IN", "VLM/LLM microservices"),
]

MISCONCEPTIONS = [
    {
        "slug": "fusion-always-wins",
        "confused": "Adding a second modality always lowers error",
        "missing_distinction": "If one modality already contains the task signal (shape centers via LiDAR), fusion may not beat the unimodal specialist (01a narrative).",
        "simple_correction": "Fusion helps when modalities are complementary, as in colored cubes — not automatically.",
        "source": {"source_type": "notebook", "file": "01a_Early_and_Late_Fusion.ipynb", "cell_index": 2},
    },
    {
        "slug": "lidar-sees-color",
        "confused": "LiDAR images look like photos so they include color",
        "missing_distinction": "The 64×64 LiDAR grid is range (and then XYZA), not RGB. Color tasks require the camera stream.",
        "simple_correction": "LiDAR does not encode red/green/blue cubes.",
        "source": {"source_type": "notebook", "file": "02a_Intermediate_Fusion.ipynb", "cell_index": 5},
    },
    {
        "slug": "late-vs-early-universal-winner",
        "confused": "Early or late fusion is globally best",
        "missing_distinction": "01a vs 02a change the task; 02a adds concat/matmul. There is no universal winner.",
        "simple_correction": "Pick the join that lets complementary signals interact at the right depth.",
        "source": {"source_type": "notebook", "file": "02a_Intermediate_Fusion.ipynb", "cell_index": 3},
    },
    {
        "slug": "matmul-is-hadamard",
        "confused": "torch.matmul is elementwise multiply",
        "missing_distinction": "Hadamard is elementwise; matmul mixes different spatial locations (02a).",
        "simple_correction": "Matmul is matrix multiply of feature maps; Hadamard is *.",
        "source": {"source_type": "notebook", "file": "02a_Intermediate_Fusion.ipynb", "cell_index": 28},
    },
    {
        "slug": "clip-is-only-text-image",
        "confused": "Contrastive pre-training means CLIP text↔image only",
        "missing_distinction": "02b uses image↔outline; 05 uses image↔LiDAR (CILP).",
        "simple_correction": "Any paired modalities can be contrastively aligned.",
        "source": {"source_type": "notebook", "file": "02b_Contrastive_Pretraining.ipynb", "cell_index": 2},
    },
    {
        "slug": "simulation-is-actual",
        "confused": "A digital twin curve is a measured training run",
        "missing_distinction": "SIMULATED_RESULT vs EXPECTED_RESULT vs ACTUAL_RUN.",
        "simple_correction": "Academy twins are educational simulators unless you import a real file.",
        "source": {"source_type": "notebook", "file": "02a_Intermediate_Fusion.ipynb", "cell_index": 5},
    },
    {
        "slug": "vss-is-one-llm-call",
        "confused": "Summarize is a single LLM completion over the whole MP4",
        "missing_distinction": "Chunk → VLM captions → caption LLM → aggregation LLM + Milvus.",
        "simple_correction": "VSS is a multi-stage CA-RAG pipeline.",
        "source": {"source_type": "notebook", "file": "04a_VSS.ipynb", "cell_index": 33},
    },
    {
        "slug": "longer-chunks-always-better",
        "confused": "Bigger chunk_duration is always higher quality",
        "missing_distinction": "Larger chunks process fewer frames; fast events can be missed (04a math).",
        "simple_correction": "Short chunks: more frames, more detail, more latency.",
        "source": {"source_type": "notebook", "file": "04a_VSS.ipynb", "cell_index": 60},
    },
    {
        "slug": "vector-rag-equals-graph-rag",
        "confused": "Vector-RAG and Graph-RAG are the same Q&A",
        "missing_distinction": "Vector: similar captions. Graph: entities/relations + Cypher. Live streams: vector only.",
        "simple_correction": "Graph-RAG is for relational video queries after enable_chat ingest.",
        "source": {"source_type": "notebook", "file": "04b_VSS_GraphRAG.ipynb", "cell_index": 1},
    },
    {
        "slug": "graph-rag-for-live-stream",
        "confused": "Use Graph-RAG on live VSS streams",
        "missing_distinction": "04b: Vector-RAG is the only supported method for live stream processing.",
        "simple_correction": "Graph-RAG is for offline/video ingestion with enable_chat.",
        "source": {"source_type": "notebook", "file": "04b_VSS_GraphRAG.ipynb", "cell_index": 1},
    },
    {
        "slug": "unfreeze-to-pass",
        "confused": "Unfreeze lidar_cnn to reach 95% RGB accuracy",
        "missing_distinction": "05 says do not unfreeze; projector + frozen head is the point.",
        "simple_correction": "Keep lidar_cnn and CILP frozen; train the projector.",
        "source": {"source_type": "notebook", "file": "05_Assessment.ipynb", "cell_index": 8},
    },
    {
        "slug": "projection-is-fusion",
        "confused": "A projector concatenates RGB and LiDAR tensors",
        "missing_distinction": "Projection maps one embedding space into another; fusion joins streams inside one net.",
        "simple_correction": "Projector is an MLP between frozen spaces.",
        "source": {"source_type": "notebook", "file": "03a_Projection.ipynb", "cell_index": 1},
    },
    {
        "slug": "aggregation-prompt-creates-new-facts",
        "confused": "A better summary_aggregation_prompt will mention events the VLM never captioned",
        "missing_distinction": "Aggregation can only use condensed captions (04a).",
        "simple_correction": "Fix the VLM prompt / chunking first; inspect Milvus.",
        "source": {"source_type": "notebook", "file": "04a_VSS.ipynb", "cell_index": 52},
    },
    {
        "slug": "azimuth-is-zenith",
        "confused": "Azimuth and zenith are interchangeable angles",
        "missing_distinction": "This LiDAR: azimuth rows / horizontal, zenith columns / vertical.",
        "simple_correction": "Two angles for 3D; conventions are sensor-specific.",
        "source": {"source_type": "notebook", "file": "01a_Early_and_Late_Fusion.ipynb", "cell_index": 16},
    },
    {
        "slug": "low-train-loss-means-solved",
        "confused": "LiDAR train loss < 1 means the cubes problem is solved",
        "missing_distinction": "Valid loss > 8 shows memorization (02a).",
        "simple_correction": "Always compare train vs valid.",
        "source": {"source_type": "notebook", "file": "02a_Intermediate_Fusion.ipynb", "cell_index": 7},
    },
    {
        "slug": "more-parameters-always-better",
        "confused": "LateNet must win because it has ~2× parameters",
        "missing_distinction": "02a: more parameters are not always better; concat has fewer than late.",
        "simple_correction": "Capacity ≠ complementary mixing.",
        "source": {"source_type": "notebook", "file": "02a_Intermediate_Fusion.ipynb", "cell_index": 26},
    },
    {
        "slug": "nv-yolox-reads-the-words",
        "confused": "NV-YOLOX OCRs the title text",
        "missing_distinction": "It predicts boxes for table/chart/title; OCR is a different stage.",
        "simple_correction": "Layout detection ≠ character recognition.",
        "source": {"source_type": "notebook", "file": "03b_OCR_Pipelines.ipynb", "cell_index": 41},
    },
    {
        "slug": "chat-works-without-ingest",
        "confused": "/chat/completions works on a raw file id with no summarize",
        "missing_distinction": "04b processes video with enable_chat to build captions/graph first.",
        "simple_correction": "Ingest, then Q&A.",
        "source": {"source_type": "notebook", "file": "04b_VSS_GraphRAG.ipynb", "cell_index": 10},
    },
    {
        "slug": "cilp-classifies-directly",
        "confused": "CILP's cosine matrix is the cube/sphere classifier",
        "missing_distinction": "CILP aligns embeddings; classification uses frozen lidar_cnn on projected features.",
        "simple_correction": "Contrastive pre-train, then project, then classify.",
        "source": {"source_type": "notebook", "file": "05_Assessment.ipynb", "cell_index": 14},
    },
    {
        "slug": "omniverse-is-the-kit-app-in-this-repo",
        "confused": "This git repo contains the Omniverse Kit twin used in class",
        "missing_distinction": "NVIDIA-MM shipped notebooks only; SDG data is not in the clone.",
        "simple_correction": "Academy twins are web simulators plus an optional bridge folder.",
        "source": {"source_type": "notebook", "file": "01a_Early_and_Late_Fusion.ipynb", "cell_index": 8},
    },
    {
        "slug": "rgb-gives-metric-depth",
        "confused": "RGB pixels are distances",
        "missing_distinction": "Distance images exist in Omniverse but are not used as a real-world instrument in the multimodal models (01a).",
        "simple_correction": "Use LiDAR (or stereo/ToF) for metric range.",
        "source": {"source_type": "notebook", "file": "01a_Early_and_Late_Fusion.ipynb", "cell_index": 12},
    },
    {
        "slug": "all-lidar-share-this-math",
        "confused": "Every LiDAR uses these azimuth/zenith formulas",
        "missing_distinction": "01a: 'This is not true of all LiDAR systems'.",
        "simple_correction": "Re-derive from that sensor's angle definition.",
        "source": {"source_type": "notebook", "file": "01a_Early_and_Late_Fusion.ipynb", "cell_index": 16},
    },
    {
        "slug": "temperature-changes-chunk-size",
        "confused": "temperature is how long each video chunk is",
        "missing_distinction": "temperature/top_p sample tokens; chunk_duration cuts the video.",
        "simple_correction": "Orthogonal knobs on /summarize.",
        "source": {"source_type": "notebook", "file": "04a_VSS.ipynb", "cell_index": 68},
    },
    {
        "slug": "milvus-stores-raw-video",
        "confused": "Milvus holds MP4 bytes",
        "missing_distinction": "It stores embeddings and caption metadata per summary id.",
        "simple_correction": "Files live in /files; captions live in Milvus.",
        "source": {"source_type": "notebook", "file": "04a_VSS.ipynb", "cell_index": 35},
    },
    {
        "slug": "9-points-optional",
        "confused": "Any assessment score is a certificate",
        "missing_distinction": "9/10 required; click ASSESS TASK on the DLI course page after pass.",
        "simple_correction": "Meet both loss and accuracy gates.",
        "source": {"source_type": "notebook", "file": "05_Assessment.ipynb", "cell_index": 46},
    },
]

MISCONCEPTIONS = MISCONCEPTIONS + EXTRA_MISCONCEPTIONS

OBJECTIVES = [
    ("obj-xyza", "Convert LiDAR depth + azimuth + zenith into XYZA", "lidar-xyza", "01a_Early_and_Late_Fusion.ipynb", 3),
    ("obj-fusion-choice", "Choose fusion depth for complementary sensors", "intermediate-concat", "02a_Intermediate_Fusion.ipynb", 5),
    ("obj-contrastive", "Implement symmetric contrastive loss", "clip-style", "02b_Contrastive_Pretraining.ipynb", 4),
    ("obj-project", "Attach a projector to a frozen unimodal embedder", "cross-modal-projection", "03a_Projection.ipynb", 5),
    ("obj-ocr", "Design a PDF multimodal extraction pipeline", "ocr", "03b_OCR_Pipelines.ipynb", 4),
    ("obj-vss", "Tune VSS prompts and chunk_duration for an ITS report", "vss-chunk-duration", "04a_VSS.ipynb", 5),
    ("obj-graph", "Explain Graph-RAG stages and Cypher retrieval", "graph-rag", "04b_VSS_GraphRAG.ipynb", 5),
    ("obj-cilp", "Pass CILP assessment gates without unfreezing lidar_cnn", "cilp", "05_Assessment.ipynb", 6),
]

TWINS_CATALOG = [
    {
        "slug": "lidar-geometry",
        "title": "LiDAR geometry",
        "summary": "Fire a simulated beam; recover XYZ with the 01a angle convention.",
        "controls": [
            {"key": "depth", "label": "Depth", "min": 0, "max": 80, "step": 0.5, "default": 25},
            {"key": "azimuth_deg", "label": "Azimuth °", "min": -90, "max": 90, "step": 1, "default": 0},
            {"key": "zenith_deg", "label": "Zenith °", "min": -45, "max": 45, "step": 1, "default": 0},
            {"key": "max_range", "label": "Max range", "min": 10, "max": 80, "step": 1, "default": 50},
            {"key": "invert_angles", "label": "Negate angles (01a default)", "type": "bool", "default": True},
        ],
    },
    {
        "slug": "fusion-lab",
        "title": "Fusion lab",
        "summary": "Compare unimodal vs early/late/concat/matmul on mixed shapes or colored cubes.",
        "controls": [
            {"key": "dataset", "label": "Dataset", "type": "enum", "options": ["mixed_shapes", "colored_cubes"], "default": "colored_cubes"},
            {"key": "architecture", "label": "Architecture", "type": "enum", "options": ["rgb", "lidar", "early", "late", "concat", "matmul"], "default": "concat"},
            {"key": "epochs", "label": "Epochs", "min": 5, "max": 40, "step": 1, "default": 20},
            {"key": "rgb_quality", "label": "RGB signal quality", "min": 0, "max": 1, "step": 0.05, "default": 0.7},
            {"key": "lidar_quality", "label": "LiDAR signal quality", "min": 0, "max": 1, "step": 0.05, "default": 0.85},
        ],
    },
    {
        "slug": "modality-explorer",
        "title": "Modality explorer",
        "summary": "Audio spectrograms, CT axes, RGB, and LiDAR representations.",
        "controls": [
            {"key": "modality", "label": "Modality", "type": "enum", "options": ["audio", "ct", "rgb", "lidar"], "default": "audio"},
            {"key": "sample_rate", "label": "Sample rate", "min": 8000, "max": 48000, "step": 1000, "default": 44100},
            {"key": "ct_axis", "label": "CT axis", "min": 0, "max": 2, "step": 1, "default": 2},
        ],
    },
    {
        "slug": "contrastive-space",
        "title": "Contrastive space",
        "summary": "All-pairs cosine matrix like 02b CLIP training.",
        "controls": [
            {"key": "batch_size", "label": "Batch size", "min": 2, "max": 12, "step": 1, "default": 6},
            {"key": "alignment", "label": "Alignment", "min": 0, "max": 1, "step": 0.05, "default": 0.82},
            {"key": "temperature", "label": "Temperature (edu)", "min": 0.02, "max": 0.5, "step": 0.01, "default": 0.07},
        ],
    },
    {
        "slug": "projection-lab",
        "title": "Projection lab",
        "summary": "Frozen encoder plus MLP projector into another embedding space.",
        "controls": [
            {"key": "in_dim", "label": "In dim", "min": 32, "max": 4096, "step": 32, "default": 200},
            {"key": "out_dim", "label": "Out dim", "min": 32, "max": 4096, "step": 32, "default": 512},
            {"key": "freeze_source", "label": "Freeze source", "type": "bool", "default": True},
            {"key": "trained_fraction", "label": "Trained fraction", "min": 0, "max": 1, "step": 0.05, "default": 0.7},
        ],
    },
    {
        "slug": "ocr-pipeline",
        "title": "OCR / PDF pipeline",
        "summary": "partition_pdf → chunk → tables/figures → NV-YOLOX.",
        "controls": [
            {"key": "chunking", "label": "Chunking", "type": "enum", "options": ["naive", "by_title"], "default": "by_title"},
            {"key": "infer_tables", "label": "Infer tables", "type": "bool", "default": True},
            {"key": "yolox", "label": "YOLOX / NV-YOLOX", "type": "bool", "default": True},
            {"key": "pages", "label": "Pages", "min": 1, "max": 40, "step": 1, "default": 12},
        ],
    },
    {
        "slug": "vss-pipeline",
        "title": "VSS CA-RAG",
        "summary": "Chunk duration vs processed frames, prompts, sampling.",
        "controls": [
            {"key": "video_length_s", "label": "Video length (s)", "min": 10, "max": 300, "step": 5, "default": 120},
            {"key": "chunk_duration_s", "label": "Chunk duration (s)", "min": 5, "max": 60, "step": 1, "default": 20},
            {"key": "chunk_overlap_s", "label": "Overlap (s)", "min": 0, "max": 10, "step": 1, "default": 0},
            {"key": "frames_per_chunk", "label": "Frames / chunk", "min": 4, "max": 16, "step": 1, "default": 10},
            {"key": "temperature", "label": "Temperature", "min": 0, "max": 1.2, "step": 0.05, "default": 0.2},
            {"key": "prompt_specificity", "label": "Prompt specificity", "min": 0, "max": 1, "step": 0.05, "default": 0.8},
        ],
    },
    {
        "slug": "graph-rag",
        "title": "Graph-RAG",
        "summary": "Warehouse entities, Cypher-shaped retrieval, vector vs graph.",
        "controls": [
            {"key": "mode", "label": "Mode", "type": "enum", "options": ["graph", "vector"], "default": "graph"},
            {"key": "enable_chat", "label": "enable_chat", "type": "bool", "default": True},
            {"key": "query", "label": "Query", "type": "text", "default": "Was the worker carrying the box wearing PPE?"},
        ],
    },
    {
        "slug": "cilp-assessment",
        "title": "CILP assessment arena",
        "summary": "Architecture defense: contrastive align, project, classify — freeze the LiDAR CNN.",
        "controls": [
            {"key": "freeze_lidar_cnn", "label": "Freeze lidar_cnn", "type": "bool", "default": True},
            {"key": "freeze_cilp", "label": "Freeze CILP after pretrain", "type": "bool", "default": True},
            {"key": "trained_fraction", "label": "Training progress", "min": 0, "max": 1, "step": 0.05, "default": 0.85},
            {"key": "cilp_emb", "label": "CILP emb", "min": 64, "max": 512, "step": 8, "default": 200},
        ],
        "suggestions": ["pass-path", "unfreeze-hurt", "undertrained", "wide-emb"],
    },
    {
        "slug": "incident-diagnosis",
        "title": "Incident diagnosis",
        "summary": "See symptoms (missed PPE, high valid error). Commit a cause before the twin reveals ground truth.",
        "controls": [
            {"key": "hypothesis", "label": "Your diagnosis", "type": "enum", "options": ["missing-graph", "long-chunks", "lidar-overfit", "unfrozen-head", "naive-chunks"], "default": "missing-graph"},
            {"key": "commit", "label": "Commit diagnosis", "type": "bool", "default": False},
        ],
        "suggestions": ["ppe-miss", "commit-wrong", "commit-right", "lidar-case"],
    },
    {
        "slug": "risk-radar",
        "title": "Operational risk radar",
        "summary": "Educational risk scores for identity collapse, missed video events, missing graphs, unfreeze, and PDF injection.",
        "controls": [
            {"key": "rgb_quality", "label": "RGB quality", "min": 0, "max": 1, "step": 0.05, "default": 0.7},
            {"key": "lidar_quality", "label": "LiDAR quality", "min": 0, "max": 1, "step": 0.05, "default": 0.85},
            {"key": "chunk_duration_s", "label": "VSS chunk (s)", "min": 5, "max": 60, "step": 1, "default": 20},
            {"key": "enable_chat", "label": "enable_chat", "type": "bool", "default": True},
            {"key": "freeze_lidar_cnn", "label": "Freeze lidar_cnn", "type": "bool", "default": True},
            {"key": "pdf_as_instructions", "label": "Treat PDF as instructions", "type": "bool", "default": False},
        ],
        "suggestions": ["prompt-inject", "evidence-mix", "gpu-hold", "no-chat"],
    },
]


def lesson_for(concept: dict) -> dict:
    slug = concept["slug"]
    return {
        "slug": f"lesson-{slug}",
        "title": f"Learn {concept['name']}",
        "concept_slug": slug,
        "twin_id": concept.get("twin_id") or "",
        "steps": [
            {"id": "explain", "kind": "EXPLAIN", "text": concept["engineer"]},
            {"id": "visualize", "kind": "VISUALIZE", "twin": concept.get("twin_id")},
            {
                "id": "predict",
                "kind": "PREDICT",
                "text": f"Before running the twin, predict what happens to the key metric if you change the main control for {concept['name']}.",
            },
            {"id": "experiment", "kind": "EXPERIMENT", "twin": concept.get("twin_id")},
            {"id": "observe", "kind": "OBSERVE", "text": "Compare your prediction to the SIMULATED_RESULT (not an ACTUAL_RUN)."},
            {"id": "explain_back", "kind": "EXPLAIN_BACK", "text": f"Explain {concept['name']} in your own words."},
            {"id": "diagnose", "kind": "DIAGNOSE", "text": "Which misconception were you closest to?"},
            {"id": "practice", "kind": "PRACTICE"},
            {"id": "mastery", "kind": "MASTERY_UPDATE"},
        ],
    }
