"""Curated operational risks for multimodal inference systems taught in this course."""

from __future__ import annotations

RISKS = [
    {
        "id": "lidar-color-blind",
        "title": "LiDAR-only identity collapse",
        "kind": "technical",
        "leading_signal": "Train error drops while validation stays high on colored cubes.",
        "spot_it_live": "Compare unimodal LiDAR vs concat on the same Omniverse split.",
        "mitigation": "Fuse RGB mid-network (concat/matmul) so color identity can bind to position.",
        "example": "02a LiDAR-only overfits because cubes share geometry.",
        "twin": "fusion-lab",
        "scenario": "lidar-overfit-cubes",
    },
    {
        "id": "angle-convention",
        "title": "Forgot negated azimuth/zenith",
        "kind": "technical",
        "leading_signal": "Point cloud looks rotated relative to RGB.",
        "spot_it_live": "Toggle invert_angles on the LiDAR geometry twin.",
        "mitigation": "Use the 01a convention: sin/cos of negated angles; mask max-range returns.",
        "example": "x = d·sin(-az)·cos(-ze).",
        "twin": "lidar-geometry",
        "scenario": "no-invert",
    },
    {
        "id": "max-range-ghosts",
        "title": "Unmasked max-range hits",
        "kind": "technical",
        "leading_signal": "A wall of points at the sensor max range.",
        "spot_it_live": "Set depth ≥ max_range in the geometry twin.",
        "mitigation": "Treat a=0 / invalid returns as missing, never as a surface.",
        "example": "01a: if the laser does not return, this family assumes max range.",
        "twin": "lidar-geometry",
        "scenario": "max-range",
    },
    {
        "id": "late-when-need-mix",
        "title": "Late fusion when streams must interact",
        "kind": "architecture",
        "leading_signal": "Each head is decent; the ensemble still misses complementary cues.",
        "spot_it_live": "Fusion lab: late vs concat on colored cubes.",
        "mitigation": "Use intermediate fusion when identity lives in one stream and pose in the other.",
        "example": "Color × geometry must mix before the final head.",
        "twin": "fusion-lab",
        "scenario": "need-intermediate",
    },
    {
        "id": "matmul-as-hadamard",
        "title": "Treating matmul as elementwise mix",
        "kind": "technical",
        "leading_signal": "Unexpected spatial mixing / worse localization.",
        "spot_it_live": "Switch concat vs matmul in fusion lab.",
        "mitigation": "Say the operator: concat stacks channels; matmul mixes locations; Hadamard is aligned multiply.",
        "example": "02a intermediate fusion cells.",
        "twin": "fusion-lab",
        "scenario": "matmul",
    },
    {
        "id": "unfreeze-assessment",
        "title": "Unfreezing lidar_cnn to 'help' CILP",
        "kind": "business",
        "leading_signal": "Assessment accuracy falls after unfreeze.",
        "spot_it_live": "CILP twin with freeze_lidar_cnn=false.",
        "mitigation": "Freeze CILP and lidar_cnn; train only the projector (05).",
        "example": "Course warns unfreeze makes the exam harder.",
        "twin": "cilp-assessment",
        "scenario": "unfreeze-hurt",
    },
    {
        "id": "chunk-too-long",
        "title": "VSS chunks hide events",
        "kind": "technical",
        "leading_signal": "Summaries miss short incidents; processed_frames is low.",
        "spot_it_live": "VSS twin: raise chunk_duration and watch frames drop.",
        "mitigation": "Shorter chunk_duration → more frames, more detail, more latency.",
        "example": "04a processed_frames = frames_per_chunk × chunks.",
        "twin": "vss-pipeline",
        "scenario": "long-chunks",
    },
    {
        "id": "generic-vss-prompt",
        "title": "Generic VSS prompt misses timestamps",
        "kind": "business",
        "leading_signal": "ITS report has no clock times or vehicle classes.",
        "spot_it_live": "Lower prompt_specificity in the VSS twin.",
        "mitigation": "Persona + format instructions; inspect Milvus dense captions.",
        "example": "04a CA-RAG prompt cells.",
        "twin": "vss-pipeline",
        "scenario": "vague-prompt",
    },
    {
        "id": "graph-without-chat",
        "title": "Graph-RAG with enable_chat=false",
        "kind": "technical",
        "leading_signal": "Relational PPE questions come back empty.",
        "spot_it_live": "Graph-RAG twin: disable enable_chat.",
        "mitigation": "Ingest with enable_chat=True so G-Extraction builds Neo4j.",
        "example": "04b warehouse graph.",
        "twin": "graph-rag",
        "scenario": "no-graph",
    },
    {
        "id": "graph-on-live",
        "title": "Graph-RAG on a live stream",
        "kind": "architecture",
        "leading_signal": "Live Q&A has no Neo4j path.",
        "spot_it_live": "Graph-RAG twin mode=vector.",
        "mitigation": "04b: live streams support Vector-RAG only.",
        "example": "Do not promise Cypher on live VSS.",
        "twin": "graph-rag",
        "scenario": "live-vector",
    },
    {
        "id": "naive-pdf-chunks",
        "title": "Naive PDF character chunks",
        "kind": "technical",
        "leading_signal": "Table rows split across chunks; titles lost.",
        "spot_it_live": "OCR twin: chunking=naive vs by_title.",
        "mitigation": "by_title + table-transformer + NV-YOLOX page-elements.",
        "example": "03b GB200 datasheet lab.",
        "twin": "ocr-pipeline",
        "scenario": "naive-chunk",
    },
    {
        "id": "pdf-as-instructions",
        "title": "PDF text treated as system instructions",
        "kind": "security",
        "leading_signal": "Extracted text tries to change the tutor or RAG prompt.",
        "spot_it_live": "Risk radar: pdf_as_instructions=true.",
        "mitigation": "Treat extracted PDF as DATA. Never execute or obey document instructions.",
        "example": "Legal/safety banner on Notebook Studio.",
        "twin": "risk-radar",
        "scenario": "prompt-inject",
    },
    {
        "id": "sim-as-actual",
        "title": "Simulation labeled as a measurement",
        "kind": "business",
        "leading_signal": "A deck cites twin curves as AIPerf.",
        "spot_it_live": "Any twin — evidence_type is SIMULATED_RESULT.",
        "mitigation": "Import real files on Experiments as ACTUAL_RUN; never overwrite raw.",
        "example": "Evidence model tests.",
        "twin": "risk-radar",
        "scenario": "evidence-mix",
    },
    {
        "id": "nyquist-alias",
        "title": "Audio above Nyquist treated as real",
        "kind": "technical",
        "leading_signal": "Spectrogram shows energy that cannot exist at that sample rate.",
        "spot_it_live": "Modality explorer: drop sample_rate.",
        "mitigation": "Highest reliable frequency is sample_rate/2 (01b).",
        "example": "WAV → FFT windows.",
        "twin": "modality-explorer",
        "scenario": "low-sr",
    },
    {
        "id": "projection-as-fusion",
        "title": "Calling a projector 'early fusion'",
        "kind": "architecture",
        "leading_signal": "Team retrains the frozen head 'because we fused'.",
        "spot_it_live": "Projection lab: freeze_source toggle.",
        "mitigation": "Projection maps spaces; fusion mixes streams. 03a/05 freeze the source.",
        "example": "CILP projector 200 → lidar_cnn.get_embs.",
        "twin": "projection-lab",
        "scenario": "unfreeze-source",
    },
    {
        "id": "clip-only-text",
        "title": "CLIP-only-means-text-image",
        "kind": "technical",
        "leading_signal": "Team skips contrastive pretrain because there is no language.",
        "spot_it_live": "Contrastive space twin.",
        "mitigation": "02b is image↔outline; 05 CILP is RGB↔LiDAR.",
        "example": "Symmetric CE on cosine matrix.",
        "twin": "contrastive-space",
        "scenario": "aligned",
    },
    {
        "id": "confounded-compare",
        "title": "Comparing runs with different splits",
        "kind": "business",
        "leading_signal": "Accuracy 'wins' after changing dataset and freeze flags together.",
        "spot_it_live": "Experiments → Detect confounders.",
        "mitigation": "Match architecture, split, freeze, chunk_duration, hardware.",
        "example": "colored_cubes vs mixed_shapes.",
        "twin": "fusion-lab",
        "scenario": "confound",
    },
    {
        "id": "kernel-poison",
        "title": "Leftover GPU kernel poisons the next lab",
        "kind": "technical",
        "leading_signal": "OOM on a tiny notebook after VSS.",
        "spot_it_live": "00 JupyterLab overview — reset is not training.",
        "mitigation": "Reset kernel / GPU memory between labs.",
        "example": "00_jupyterlab.ipynb.",
        "twin": "risk-radar",
        "scenario": "gpu-hold",
    },
    {
        "id": "caption-not-graph",
        "title": "Dense captions mistaken for a knowledge graph",
        "kind": "technical",
        "leading_signal": "'Who wore PPE' answered from nearest caption only.",
        "spot_it_live": "Incident twin: relational question.",
        "mitigation": "G-Extraction → Cypher → G-Generation when relations matter.",
        "example": "04b warehouse.",
        "twin": "incident-diagnosis",
        "scenario": "ppe-miss",
    },
    {
        "id": "cameras-cheaper-claim",
        "title": "Shipping RGB as a drop-in LiDAR replacement",
        "kind": "business",
        "leading_signal": "Product claims metric depth from RGB alone.",
        "spot_it_live": "CILP assessment: RGB reuses a LiDAR head only after alignment.",
        "mitigation": "CILP + projector is transfer, not a free depth sensor.",
        "example": "05 gates: loss < 3.5 and acc path.",
        "twin": "cilp-assessment",
        "scenario": "pass-path",
    },
]
